receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch: {}
  memory_limiter:
    check_interval: 2s
    limit_mib: 400
    spike_limit_mib: 200

exporters:
  # Example: forward traces+metrics to Tempo
  otlphttp:
    endpoint: http://tempo:4318
  debug: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp, debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp]
