services:
  relay:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    # Uses a named Docker volume for portability (no host folder permission issues)
    volumes:
      - nodered-data:/data
    restart: unless-stopped

volumes:
  nodered-data:
 